# Generated by Django 4.1.3 on 2023-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
