# Generated by Django 4.1.3 on 2023-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0003_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
