# Generated by Django 4.1.3 on 2023-02-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Panel.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Panel.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Panel.technology'),
        ),
    ]
